apiVersion: apps/v1
kind: Deployment
metadata:
  name: wapp-deployment
  labels:
    app: wapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wapp
  template:
    metadata:
      labels:
        app: wapp
    spec:
      containers:
      - name: wapp
        image: wapp:1.0.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wapp-servie
spec:
  selector:
    app.kubernetes.io/name: wapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80